[build]
  command = "npm run build"
  publish = "frontend/dist"
  functions = "netlify/functions"

[build.environment]
  NODE_ENV = "production"
  METAL_API_KEY = "ecefa0f880c0c94dd28bc94da727246b"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200